# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_withPL/system_withPL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_withPL || ORIG_REF_NAME==system_withPL}]

# IP: bd/system_withPL/ip/system_withPL_processing_system7_0_0/system_withPL_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_withPL_processing_system7_0_0 || ORIG_REF_NAME==system_withPL_processing_system7_0_0}]

# IP: bd/system_withPL/ip/system_withPL_Adams_Peripheral_0_0/system_withPL_Adams_Peripheral_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_withPL_Adams_Peripheral_0_0 || ORIG_REF_NAME==system_withPL_Adams_Peripheral_0_0}]

# IP: bd/system_withPL/ip/system_withPL_processing_system7_0_axi_periph_1/system_withPL_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_withPL_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==system_withPL_processing_system7_0_axi_periph_1}]

# IP: bd/system_withPL/ip/system_withPL_rst_processing_system7_0_100M_0/system_withPL_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_withPL_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_withPL_rst_processing_system7_0_100M_0}]

# IP: bd/system_withPL/ip/system_withPL_auto_pc_11/system_withPL_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_withPL_auto_pc_11 || ORIG_REF_NAME==system_withPL_auto_pc_11}]

# XDC: bd/system_withPL/ip/system_withPL_processing_system7_0_0/system_withPL_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_withPL_processing_system7_0_0 || ORIG_REF_NAME==system_withPL_processing_system7_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system_withPL/ip/system_withPL_rst_processing_system7_0_100M_0/system_withPL_rst_processing_system7_0_100M_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_withPL_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_withPL_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/system_withPL/ip/system_withPL_rst_processing_system7_0_100M_0/system_withPL_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/system_withPL/ip/system_withPL_rst_processing_system7_0_100M_0/system_withPL_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_withPL_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_withPL_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/system_withPL/ip/system_withPL_auto_pc_11/system_withPL_auto_pc_11_ooc.xdc

# XDC: bd/system_withPL/system_withPL_ooc.xdc
