//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XilinxTester.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XilinxTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ALU测试 的本地化字符串。
        /// </summary>
        public static string STR_ALU_TEST {
            get {
                return ResourceManager.GetString("STR_ALU_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率 的本地化字符串。
        /// </summary>
        public static string STR_BAUDRATE {
            get {
                return ResourceManager.GetString("STR_BAUDRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string STR_CANCEL {
            get {
                return ResourceManager.GetString("STR_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位 的本地化字符串。
        /// </summary>
        public static string STR_DATABITS {
            get {
                return ResourceManager.GetString("STR_DATABITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DMA测试 的本地化字符串。
        /// </summary>
        public static string STR_DMA_TEST {
            get {
                return ResourceManager.GetString("STR_DMA_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存测试 的本地化字符串。
        /// </summary>
        public static string STR_MEMORY_TEST {
            get {
                return ResourceManager.GetString("STR_MEMORY_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string STR_OK {
            get {
                return ResourceManager.GetString("STR_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奇偶位 的本地化字符串。
        /// </summary>
        public static string STR_PARITY {
            get {
                return ResourceManager.GetString("STR_PARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口名称 的本地化字符串。
        /// </summary>
        public static string STR_PORTNAME {
            get {
                return ResourceManager.GetString("STR_PORTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PS测试 的本地化字符串。
        /// </summary>
        public static string STR_PS_TEST {
            get {
                return ResourceManager.GetString("STR_PS_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位 的本地化字符串。
        /// </summary>
        public static string STR_STOPBITS {
            get {
                return ResourceManager.GetString("STR_STOPBITS", resourceCulture);
            }
        }
    }
}
